
name: 'social_cloud' # Nombre del proyecto
version: '1.0.0' # Versión del proyecto
config-version: 2 # dbt usa la estructura v2

profile: 'default' # Perfil que va a usar dbt para conectarse al almacén de datos. Si está por defecto, usa el perfíl que se puso en la conexión.

# Configuración de dbt que le especifica a donde tiene que mirar para los diferentes tipos de ficheros.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # Directorio donde se encuentra los ficheros compilados de SQL
clean-targets: # Directorios que se tienen que limpiar en un `dbt clean` 
  - "target"
  - "dbt_packages"


# Configuración de los modelos
# Toda la documentación: https://docs.getdbt.com/docs/configuring-models
# En dbt, la materialización por defecto son vistas, es decir, cuando haces un dbt run o dbt build, todos los modelos se construiran como vistas si no está especificado
# La configuración de abajo sobreescribe la materialización por defecto.
# Se puede añadir esta configuración en los modelos con el macro: `{{ config(...) }}`
models:
  social_cloud:
    staging:
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_SOCIAL_CLOUD_SILVER_DB"
      +schema: staging
      +materialized: view 
      # En staging se materializa como vistas para que obtenga los datos más frescos posibles (la consulta SQL se ejecuta cada vez zque se consulta la vista). Además, evita desperdiciar espacio en el almacén en modelos que no están pensados para ser consultados por los consumidores de datos (se almacena la lógica, no los datos).
    
    intermediate:
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_SOCIAL_CLOUD_SILVER_DB"
      +schema: intermediate
      +materialized: view

    marts:
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_SOCIAL_CLOUD_GOLD_DB"
      +schema: marts
      +materialized: table

snapshots: 
  social_cloud:
    +transient: false # No quiero que sea transient, porque las transient no tienen time travel.
    +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_SOCIAL_CLOUD_SILVER_DB" # Base de datos donde se materializa
    +schema: snapshots # Schema donde se materializa